version: "3"

services:
    db:
        image: mysql:8.0.20
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - "db_app:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - ${MYSQL_PORT}:3306
        networks:
            - php
    php:
        build: docker/php
        volumes:
            - ./:/var/www/
        networks:
            - php
    nginx:
        build: docker/nginx
        volumes:
            - ./:/var/www/
        ports:
            - 80:80
        networks:
            - php
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        ports:
            - 8088:80
        networks:
            - db
            - php

volumes:
    db_app:

networks:
    php:
    db:
